### ISSUE TITLE
Cannot remove users

### ISSUE THREAD

**Issue by knightsg** [philsch/ansible-redshift#15]
I'm trying to remove a user by setting state to 'absent' but it doesn't work. After the task executes the user still exists and I can log in with it. For the record, when the task executes ansible shows it as green (no change). I'm not sure why.
```

- name: Remove user
  redshift_user:
    login_user: root
    login_password: "{{ redshift_password }}"
    login_host: "{{ redshift.host }}"
    db: "{{ redshift.name }}"
    user: guy
    password: "{{ password }}"
    state: absent
```

```
usename | usesysid | usecreatedb | usesuper | usecatupd | passwd | valuntil | useconfig
-- | -- | -- | -- | -- | -- | -- | --
guy | 103 | false | false | false | ********
```
